# Generated by Django 3.0 on 2021-08-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.TimeField()),
            ],
        ),
    ]
