# Generated by Django 3.0 on 2021-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q5', '0002_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
